
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-04-12T18:03:29-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "c1d0a02f55ab43f9a69f5c55d99697536a5b97f2",
 "version": "2.34.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
