# Generated by Django 3.2.24 on 2024-03-17 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0052_fix_interface_redundancy_group_created'),
        ('slurpit_nautobot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slurpitplanning',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='slurpitimporteddevice',
            name='mapped_device',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slurpit_imported_devices', to='dcim.device'),
        ),
        migrations.AlterField(
            model_name='slurpitimporteddevice',
            name='mapped_devicetype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slurpit_imported_devices', to='dcim.devicetype'),
        ),
    ]
