
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-04-19T16:26:04+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "2890f80b1c0b231b1b86ca942a9ef1df7e036ca9",
 "version": "5.6.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
