# coding: utf-8

"""
    IcoTest Voice

    IcoTest Voice API

    The version of the OpenAPI document: 1.0.43
    Contact: shaun.hirst@3adesign.co.uk
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from icotest_voice.models.controller import Controller

class TestController(unittest.TestCase):
    """Controller unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Controller:
        """Test Controller
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Controller`
        """
        model = Controller()
        if include_optional:
            return Controller(
                controller_id = '10cda64a-0dce-4663-8b47-6ec1867f9568',
                controller_type = 'dect',
                description = 'example controller',
                location = 'server 1 rack 1',
                callback_url = 'https://server:port',
                created = '2021-06-24T14:15:22Z',
                last_contact = '2021-06-24T14:15:22Z'
            )
        else:
            return Controller(
                controller_id = '10cda64a-0dce-4663-8b47-6ec1867f9568',
                controller_type = 'dect',
        )
        """

    def testController(self):
        """Test Controller"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
