# coding: utf-8

"""
    IcoTest Voice

    IcoTest Voice API

    The version of the OpenAPI document: 1.0.43
    Contact: shaun.hirst@3adesign.co.uk
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from icotest_voice.models.request import Request

class TestRequest(unittest.TestCase):
    """Request unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Request:
        """Test Request
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Request`
        """
        model = Request()
        if include_optional:
            return Request(
                request_id = 'bc331ccb-5841-44ec-9d32-4f4fe0c3c16d',
                device_id = '5ad25725-8be0-489d-9b26-c0299a76e136',
                status = 'pending',
                message = 'message...',
                action = 'register',
                request_params = [
                    None
                    ],
                created = '2021-06-24T14:15:22Z',
                updated = '2021-06-24T14:15:22Z',
                controller_id = '10cda64a-0dce-4663-8b47-6ec1867f9568'
            )
        else:
            return Request(
                request_id = 'bc331ccb-5841-44ec-9d32-4f4fe0c3c16d',
                status = 'pending',
                action = 'register',
                created = '2021-06-24T14:15:22Z',
        )
        """

    def testRequest(self):
        """Test Request"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
