# coding: utf-8

"""
    IcoTest Voice

    IcoTest Voice API

    The version of the OpenAPI document: 1.0.43
    Contact: shaun.hirst@3adesign.co.uk
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from icotest_voice.api.requests_api import RequestsApi


class TestRequestsApi(unittest.TestCase):
    """RequestsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RequestsApi()

    def tearDown(self) -> None:
        pass

    def test_dect_get_last_commands(self) -> None:
        """Test case for dect_get_last_commands

        DECT Get Last Commands
        """
        pass

    def test_delete_appium_all_screenshots(self) -> None:
        """Test case for delete_appium_all_screenshots

        DELETE APPIUM all screenshots
        """
        pass

    def test_delete_appium_ios_certificates(self) -> None:
        """Test case for delete_appium_ios_certificates

        DELETE APPIUM audio playback file
        """
        pass

    def test_delete_audio_playback_file(self) -> None:
        """Test case for delete_audio_playback_file

        DELETE audio playback file
        """
        pass

    def test_delete_request(self) -> None:
        """Test case for delete_request

        DELETE request
        """
        pass

    def test_delete_result_file(self) -> None:
        """Test case for delete_result_file

        DELETE result file
        """
        pass

    def test_delete_result_files_in_range(self) -> None:
        """Test case for delete_result_files_in_range

        DELETE result files in date-time range
        """
        pass

    def test_get_appium_device_screenshot_list(self) -> None:
        """Test case for get_appium_device_screenshot_list

        GET APPIUM device screenshot list
        """
        pass

    def test_get_appium_retrieve_device_screenshot(self) -> None:
        """Test case for get_appium_retrieve_device_screenshot

        GET APPIUM retrieve screenshot
        """
        pass

    def test_get_audio_playback_file_list(self) -> None:
        """Test case for get_audio_playback_file_list

        GET audio playback file list
        """
        pass

    def test_get_requests(self) -> None:
        """Test case for get_requests

        GET requests
        """
        pass

    def test_get_retrieve_test_result_file(self) -> None:
        """Test case for get_retrieve_test_result_file

        GET test result file
        """
        pass

    def test_get_test_result_file_list(self) -> None:
        """Test case for get_test_result_file_list

        GET test result file list
        """
        pass

    def test_post_request_heartbeat(self) -> None:
        """Test case for post_request_heartbeat

        POST request heartbeat
        """
        pass

    def test_put_appium_install_ios_webdriveragent(self) -> None:
        """Test case for put_appium_install_ios_webdriveragent

        PUT APPIUM install ios webdriveragent
        """
        pass

    def test_put_appium_upload_ios_certificates(self) -> None:
        """Test case for put_appium_upload_ios_certificates

        PUT APPIUM upload ios certificates
        """
        pass

    def test_put_request(self) -> None:
        """Test case for put_request

        PUT request
        """
        pass

    def test_put_request_status(self) -> None:
        """Test case for put_request_status

        PUT request status
        """
        pass

    def test_put_upload_audio_playback_file(self) -> None:
        """Test case for put_upload_audio_playback_file

        PUT upload audio playback file
        """
        pass


if __name__ == '__main__':
    unittest.main()
