# Autogenerated by devscripts/update-version.py

__version__ = '2024.04.18.232703'

RELEASE_GIT_HEAD = 'c9ce57d9bf51541da2381d99bc096a9d0ddf1f27'

VARIANT = 'pip'

UPDATE_HINT = 'You installed yt-dlp with pip or using the wheel from PyPi; Use that to update'

CHANNEL = 'nightly'

ORIGIN = 'yt-dlp/yt-dlp-nightly-builds'

_pkg_version = '2024.04.18.232703dev'
