# coding: utf-8
# Generated by setup.py for PyCBC on 2024-04-19 18:27:19 +0000.

version = '2.1.6'
date = '2024-04-19 09:04:27 +0000'
release = True
last_release = '2.4.0'

git_hash = '8b331769da4a6be2941d63bee6e5d052c40679e1'
git_branch = 'None'
git_tag = 'v2.1.6'
git_author = 'maxtrevor <65971534+maxtrevor@users.noreply.github.com>'
git_committer = 'GitHub <noreply@github.com>'
git_status = 'CLEAN: All modifications committed'
git_builder = 'Unknown User <>'
git_build_date = '2024-04-19 18:27:19 +0000'
git_verbose_msg = """Version: 2.1.6
Branch: None
Tag: v2.1.6
Id: 8b331769da4a6be2941d63bee6e5d052c40679e1
Builder: Unknown User <>
Build date: 2024-04-19 18:27:19 +0000
Repository status is CLEAN: All modifications committed"""
from pycbc._version import *
