# Stub file for OneAcl class
from typing import Tuple, Union

class OneAcl:
    def parse_users(self, users: str) -> str: ...
    def parse_resources(self, resources: str) -> str: ...
    def parse_rights(self, rights: str) -> str: ...
    def parse_zone(self, zone: str) -> str: ...
    def parse_rule(self, rule_str: str) -> Union[Tuple[str, str, str], Tuple[str, str, str, str]]: ...
    def calculate_ids(self, id_str: str) -> int: ...

# Constants for user and resource identifiers
USERS: dict[str, int]
RESOURCES: dict[str, int]
RIGHTS: dict[str, int]

