# Stub file for the OneServerTester module within the PyONE library

from collections import OrderedDict
from typing import Any, Dict, List, Optional, Tuple

from . import OneServer

class OneServerTester(OneServer):
    def __init__(self, uri: str, session: str, fixture_file: Optional[str] = None, fixture_unit: Optional[str] = None, timeout: Optional[int] = None, fixture_replay: Optional[bool] = None, **options: Any) -> None: ...
    def set_fixture_unit_test(self, name: str) -> None: ...
    def _fixture_signature(self, methodname: str, params: List[Any]) -> str: ...
    def _get_fixture(self, methodname: str, params: List[Any]) -> Dict[str, Any]: ...
    def _set_fixture(self, methodname: str, params: List[Any], object: Any) -> None: ...
    def _do_request(self, method: str, params: Tuple[Any, ...]) -> Any: ...
    def _cast_parms(self, params: Tuple[Any, ...]) -> Tuple[Any, ...]: ...
    def _to_ordered_dict(self, param: Dict) -> OrderedDict: ...
    def server_retry_interval(self) -> int: ...
    def server_close(self) -> None: ...
