
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-04-19T14:38:25-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "3d511a243503064f681f913ebaca99cfe58f895a",
 "version": "5.4.33"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
