
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-04-17T11:56:39-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "3cd4a0f05232cc58a31b8a20e5848b74dc7ae9bb",
 "version": "2.8.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
