
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-04-19T14:38:26-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "c775f091c304caa078b2f313e8a057d80d875498",
 "version": "5.2.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
