
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-04-19T10:12:40-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "6e428c3f4a41b94f90209f384d0b61755c368413",
 "version": "4.17.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
