
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-04-15T14:51:35-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "a613b00abdb1ff1809a10b82096947803834cec5",
 "version": "2.2.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
