
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-04-12T15:00:56-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "a9d3ea99176fb3b45b534fa68cff379f2d6206c9",
 "version": "2.34.1b0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
