import ghidra.pcode.emu.unix
import java.lang
import java.util


class BytesEmuUnixFileSystem(ghidra.pcode.emu.unix.AbstractEmuUnixFileSystem):




    def __init__(self): ...



    def createOrGetFile(self, __a0: unicode, __a1: int) -> ghidra.pcode.emu.unix.EmuUnixFile: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getFile(self, __a0: unicode) -> ghidra.pcode.emu.unix.EmuUnixFile: ...

    def hashCode(self) -> int: ...

    def newFile(self, __a0: unicode, __a1: int) -> ghidra.pcode.emu.unix.EmuUnixFile: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def open(self, __a0: unicode, __a1: java.util.Set, __a2: ghidra.pcode.emu.unix.EmuUnixUser, __a3: int) -> ghidra.pcode.emu.unix.EmuUnixFile: ...

    def putFile(self, __a0: unicode, __a1: ghidra.pcode.emu.unix.EmuUnixFile) -> None: ...

    def toString(self) -> unicode: ...

    def unlink(self, __a0: unicode, __a1: ghidra.pcode.emu.unix.EmuUnixUser) -> None: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

