import ghidra.pcode.emu.unix
import java.lang


class EmuUnixFileDescriptor(object):
    FD_STDERR: int = 2
    FD_STDIN: int = 0
    FD_STDOUT: int = 1







    def close(self) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getOffset(self) -> object: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def read(self, __a0: object) -> object: ...

    def seek(self, __a0: object) -> None: ...

    def stat(self) -> ghidra.pcode.emu.unix.EmuUnixFileStat: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    def write(self, __a0: object) -> object: ...

    @property
    def offset(self) -> object: ...