
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-04-19T04:42:52+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "a99725ca90b608cc462775d293f879007e2e49d2",
 "version": "0.14.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
