# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_cons.ipynb.

# %% auto 0
__all__ = ['FIT', 'VAL', 'TEST', 'PRED', 'FORMAT', 'OUTPUT', 'DATASET_CLS', 'DATAFRAME_FN']

# %% ../nbs/01_cons.ipynb 6
#| export


# %% ../nbs/01_cons.ipynb 8
#| export

# %% ../nbs/01_cons.ipynb 10
#| export


# %% ../nbs/01_cons.ipynb 12
#| export


# %% ../nbs/01_cons.ipynb 14
#| export


# %% ../nbs/01_cons.ipynb 16
FIT = 'fit'
VAL = 'val'
TEST = 'test'
PRED = 'pred'
FORMAT = 'format'
OUTPUT = 'output'
DATASET_CLS = 'dataset_cls'
DATAFRAME_FN = 'dataframe_fn'

# %% ../nbs/01_cons.ipynb 18
#| export
