# Generated by sila2.code_generator; sila2.__version__: 0.12.2
from __future__ import annotations

from typing import NamedTuple


class LockServer_Responses(NamedTuple):

    pass


class UnlockServer_Responses(NamedTuple):

    pass
