# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: iscp2/v1/e2e_call.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from .extensions import e2e_call_pb2 as iscp2_dot_v1_dot_extensions_dot_e2e__call__pb2
from . import result_code_pb2 as iscp2_dot_v1_dot_result__code__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17iscp2/v1/e2e_call.proto\x12\x08iscp2.v1\x1a\"iscp2/v1/extensions/e2e_call.proto\x1a\x1aiscp2/v1/result_code.proto\"\x9e\x02\n\x0cUpstreamCall\x12\x17\n\x07\x63\x61ll_id\x18\x01 \x01(\tR\x06\x63\x61llId\x12&\n\x0frequest_call_id\x18\x02 \x01(\tR\rrequestCallId\x12.\n\x13\x64\x65stination_node_id\x18\x03 \x01(\tR\x11\x64\x65stinationNodeId\x12\x12\n\x04name\x18\x04 \x01(\tR\x04name\x12\x12\n\x04type\x18\x05 \x01(\tR\x04type\x12\x18\n\x07payload\x18\x06 \x01(\x0cR\x07payload\x12[\n\x10\x65xtension_fields\x18\x07 \x01(\x0b\x32\x30.iscp2.v1.extensions.UpstreamCallExtensionFieldsR\x0f\x65xtensionFields\"\xe6\x01\n\x0fUpstreamCallAck\x12\x17\n\x07\x63\x61ll_id\x18\x01 \x01(\tR\x06\x63\x61llId\x12\x35\n\x0bresult_code\x18\x02 \x01(\x0e\x32\x14.iscp2.v1.ResultCodeR\nresultCode\x12#\n\rresult_string\x18\x03 \x01(\tR\x0cresultString\x12^\n\x10\x65xtension_fields\x18\x04 \x01(\x0b\x32\x33.iscp2.v1.extensions.UpstreamCallAckExtensionFieldsR\x0f\x65xtensionFields\"\x98\x02\n\x0e\x44ownstreamCall\x12\x17\n\x07\x63\x61ll_id\x18\x01 \x01(\tR\x06\x63\x61llId\x12&\n\x0frequest_call_id\x18\x02 \x01(\tR\rrequestCallId\x12$\n\x0esource_node_id\x18\x03 \x01(\tR\x0csourceNodeId\x12\x12\n\x04name\x18\x04 \x01(\tR\x04name\x12\x12\n\x04type\x18\x05 \x01(\tR\x04type\x12\x18\n\x07payload\x18\x06 \x01(\x0cR\x07payload\x12]\n\x10\x65xtension_fields\x18\x07 \x01(\x0b\x32\x32.iscp2.v1.extensions.DownstreamCallExtensionFieldsR\x0f\x65xtensionFieldsB]\n\x0c\x63om.iscp2.v1B\x0c\x45\x32\x65\x43\x61llProtoP\x01\xa2\x02\x03IXX\xaa\x02\x08Iscp2.V1\xca\x02\x08Iscp2\\V1\xe2\x02\x14Iscp2\\V1\\GPBMetadata\xea\x02\tIscp2::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'iscp2.v1.e2e_call_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\014com.iscp2.v1B\014E2eCallProtoP\001\242\002\003IXX\252\002\010Iscp2.V1\312\002\010Iscp2\\V1\342\002\024Iscp2\\V1\\GPBMetadata\352\002\tIscp2::V1'
  _globals['_UPSTREAMCALL']._serialized_start=102
  _globals['_UPSTREAMCALL']._serialized_end=388
  _globals['_UPSTREAMCALLACK']._serialized_start=391
  _globals['_UPSTREAMCALLACK']._serialized_end=621
  _globals['_DOWNSTREAMCALL']._serialized_start=624
  _globals['_DOWNSTREAMCALL']._serialized_end=904
# @@protoc_insertion_point(module_scope)
