# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: iscp2/v1/ping_pong.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from .extensions import ping_pong_pb2 as iscp2_dot_v1_dot_extensions_dot_ping__pong__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18iscp2/v1/ping_pong.proto\x12\x08iscp2.v1\x1a#iscp2/v1/extensions/ping_pong.proto\"z\n\x04Ping\x12\x1d\n\nrequest_id\x18\x01 \x01(\rR\trequestId\x12S\n\x10\x65xtension_fields\x18\x02 \x01(\x0b\x32(.iscp2.v1.extensions.PingExtensionFieldsR\x0f\x65xtensionFields\"z\n\x04Pong\x12\x1d\n\nrequest_id\x18\x01 \x01(\rR\trequestId\x12S\n\x10\x65xtension_fields\x18\x02 \x01(\x0b\x32(.iscp2.v1.extensions.PongExtensionFieldsR\x0f\x65xtensionFieldsB^\n\x0c\x63om.iscp2.v1B\rPingPongProtoP\x01\xa2\x02\x03IXX\xaa\x02\x08Iscp2.V1\xca\x02\x08Iscp2\\V1\xe2\x02\x14Iscp2\\V1\\GPBMetadata\xea\x02\tIscp2::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'iscp2.v1.ping_pong_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\014com.iscp2.v1B\rPingPongProtoP\001\242\002\003IXX\252\002\010Iscp2.V1\312\002\010Iscp2\\V1\342\002\024Iscp2\\V1\\GPBMetadata\352\002\tIscp2::V1'
  _globals['_PING']._serialized_start=75
  _globals['_PING']._serialized_end=197
  _globals['_PONG']._serialized_start=199
  _globals['_PONG']._serialized_end=321
# @@protoc_insertion_point(module_scope)
