
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-04-17T14:42:35+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "8482c6776b45e698e7cf28935900fadbeddb1c27",
 "version": "0.18"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
