import ghidra.debug.api.progress
import java.lang
import java.util


class ProgressService(object):








    def addProgressListener(self, __a0: ghidra.debug.api.progress.ProgressListener) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    def getAllMonitors(self) -> java.util.Collection: ...

    def getClass(self) -> java.lang.Class: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def publishTask(self) -> ghidra.debug.api.progress.CloseableTaskMonitor: ...

    def removeProgressListener(self, __a0: ghidra.debug.api.progress.ProgressListener) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def allMonitors(self) -> java.util.Collection: ...