class ColorizeError(Exception): ...

def colorize(
    source: str,
    file: str = "inline",
    wrap: int | None = None,
    supports_color: bool = True,
) -> str: ...
def escape(source: str) -> str: ...
