# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: iscp2/v1/extensions/ping_pong.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#iscp2/v1/extensions/ping_pong.proto\x12\x13iscp2.v1.extensions\"\x15\n\x13PingExtensionFields\"\x15\n\x13PongExtensionFieldsB\x96\x01\n\x17\x63om.iscp2.v1.extensionsB\rPingPongProtoP\x01\xa2\x02\x03IVE\xaa\x02\x13Iscp2.V1.Extensions\xca\x02\x13Iscp2\\V1\\Extensions\xe2\x02\x1fIscp2\\V1\\Extensions\\GPBMetadata\xea\x02\x15Iscp2::V1::Extensionsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'iscp2.v1.extensions.ping_pong_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\027com.iscp2.v1.extensionsB\rPingPongProtoP\001\242\002\003IVE\252\002\023Iscp2.V1.Extensions\312\002\023Iscp2\\V1\\Extensions\342\002\037Iscp2\\V1\\Extensions\\GPBMetadata\352\002\025Iscp2::V1::Extensions'
  _globals['_PINGEXTENSIONFIELDS']._serialized_start=60
  _globals['_PINGEXTENSIONFIELDS']._serialized_end=81
  _globals['_PONGEXTENSIONFIELDS']._serialized_start=83
  _globals['_PONGEXTENSIONFIELDS']._serialized_end=104
# @@protoc_insertion_point(module_scope)
