# This file automatically generated by
#    /home/couchbase/jenkins/workspace/python/sdk/python-scripted-build-pipeline/py-client/couchbase_version.py
# at
#    2024-04-17 23:01:14.921128
__version__ = '4.2.1'