
# This file was generated by 'versioneer.py' (0.23.dev0) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-04-19T23:11:10+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "429c8cfe6836de1ad1d7a50c5085c627b7b2bef2",
 "version": "1.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
