
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-04-19T14:23:50+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "37de94f181b9a97eebd21460f4df63ae4a0750f8",
 "version": "0.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
