
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-04-15T19:04:30-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "2c12024229cc66553514e68c2a9e02a6c9839730",
 "version": "0.8.2rc3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
