
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-04-15T13:14:55+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "44362ac2c337ab6f8c922f1669d266f48a855af5",
 "version": "1.0.72"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
