
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-04-18T21:41:41-0500",
 "dirty": true,
 "error": null,
 "full-revisionid": "b2acfd0967f8fb219a145e98eff5c8e33c1e779f",
 "version": "0.2.13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
