
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-04-16T10:49:39+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "493a77a1d58ea2a7865881dc9948663f302e3522",
 "version": "3.0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
