
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-04-15T21:23:26+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "978bf36bfe54eeef8b2d5ebe2d64ffa57dd2c8db",
 "version": "2.5.0.post0.dev145"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
