
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-04-14T19:28:18-0500",
 "dirty": true,
 "error": null,
 "full-revisionid": "5147bc2238e180ed9607c76b2c82d08259391af5",
 "version": "0.2.16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
