import ghidra.app.plugin.core.debug.disassemble
import ghidra.framework.plugintool
import ghidra.program.model.address
import ghidra.program.model.lang
import ghidra.trace.model
import ghidra.trace.model.thread
import java.lang


class ArmDisassemblyInject(object, ghidra.app.plugin.core.debug.disassemble.DisassemblyInject):




    def __init__(self): ...



    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getInfo(self) -> ghidra.app.plugin.core.debug.disassemble.DisassemblyInjectInfo: ...

    def getPriority(self) -> int: ...

    def hashCode(self) -> int: ...

    def isApplicable(self, __a0: ghidra.trace.model.Trace) -> bool: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def post(self, __a0: ghidra.framework.plugintool.PluginTool, __a1: ghidra.trace.model.Trace, __a2: long, __a3: ghidra.program.model.address.AddressSetView) -> None: ...

    def pre(self, __a0: ghidra.framework.plugintool.PluginTool, __a1: ghidra.app.plugin.core.debug.disassemble.TraceDisassembleCommand, __a2: ghidra.trace.model.Trace, __a3: ghidra.program.model.lang.Language, __a4: long, __a5: ghidra.trace.model.thread.TraceThread, __a6: ghidra.program.model.address.AddressSetView, __a7: ghidra.program.model.address.AddressSetView) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def info(self) -> ghidra.app.plugin.core.debug.disassemble.DisassemblyInjectInfo: ...

    @property
    def priority(self) -> int: ...