# Generated by Django 3.2.22 on 2023-10-17 12:18

import datetime
from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields
import nobinobi_daily_follow_up.models


class Migration(migrations.Migration):

    dependencies = [
        ('nobinobi_staff', '0010_auto_20201029_1500'),
        ('nobinobi_child', '0014_auto_20230201_1155'),
        ('nobinobi_daily_follow_up', '0002_auto_20230201_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaperchange',
            name='_comment_excerpt',
            field=models.TextField(default='', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diaperchange',
            name='comment',
            field=model_utils.fields.SplitField(blank=True, no_excerpt_field=True, null=True, verbose_name='Comment'),
        ),
    ]
