
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-04-16T11:35:32+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "a5d6e1b4d34f1a5265d6d181bb14e6803feccd84",
 "version": "1.5.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
