# constants.py

# Default values
DEFAULT_CONTENT_PATH = "/var/tmp/"
DEFAULT_CONTENT_FILE = "panupv2-all-contents-8834-8684"
DEFAULT_PAN_HOSTNAME = "192.168.1.1"
DEFAULT_PAN_USERNAME = "admin"
DEFAULT_PAN_PASSWORD = "PaloAltoNetworks123"
DEFAULT_PAN_PASSWORD_DEFAULT = "admin"
DEFAULT_LOG_LEVEL = "INFO"

# Timeout values
MONITOR_JOB_STATUS_TIMEOUT = 30
SCP_IMPORT_TIMEOUT = 30
