
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-04-19T18:33:39+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "2a01c2121ac55a5364781c2e8eab5b45bac5f61d",
 "version": "3.0.2.post0.dev26"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
