
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-04-14T20:57:18-0500",
 "dirty": true,
 "error": null,
 "full-revisionid": "b41c8ba2589df4beac4b7e4cd34292c9d130c319",
 "version": "0.1.26"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
