# Generated by Django 2.2.28 on 2023-06-20 12:52

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_simple_notes", "0003_auto_20230620_1207"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=512, verbose_name="Category")),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.RemoveField(
            model_name="simplenote",
            name="categories",
        ),
        migrations.AddField(
            model_name="simplenote",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="notes", to="django_simple_notes.Category"
            ),
        ),
    ]
