# Generated by Django 3.2.25 on 2024-04-17 14:40

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('filer', '0017_image__transparent'),
        ('django_simple_notes', '0005_auto_20231030_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplefile',
            name='file',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.file', verbose_name='Files'),
        ),
        migrations.AlterField(
            model_name='simplenote',
            name='site',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='sites.site'),
        ),
    ]
