# coding: utf-8

"""
    Command Center operations

    Command Center operations  # noqa: E501

    OpenAPI spec version: 23.09
    Contact: support@zadarastorage.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import CommandCenter
from CommandCenter.models.inline_response200131_network_configuration_vc1 import InlineResponse200131NetworkConfigurationVc1  # noqa: E501
from CommandCenter.rest import ApiException


class TestInlineResponse200131NetworkConfigurationVc1(unittest.TestCase):
    """InlineResponse200131NetworkConfigurationVc1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse200131NetworkConfigurationVc1(self):
        """Test InlineResponse200131NetworkConfigurationVc1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CommandCenter.models.inline_response200131_network_configuration_vc1.InlineResponse200131NetworkConfigurationVc1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
