# coding: utf-8

"""
    Command Center operations

    Command Center operations  # noqa: E501

    OpenAPI spec version: 23.09
    Contact: support@zadarastorage.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import CommandCenter
from CommandCenter.models.inline_response20099_pools import InlineResponse20099Pools  # noqa: E501
from CommandCenter.rest import ApiException


class TestInlineResponse20099Pools(unittest.TestCase):
    """InlineResponse20099Pools unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20099Pools(self):
        """Test InlineResponse20099Pools"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CommandCenter.models.inline_response20099_pools.InlineResponse20099Pools()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
