# coding: utf-8

"""
    Command Center operations

    Command Center operations  # noqa: E501

    OpenAPI spec version: 23.09
    Contact: support@zadarastorage.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import CommandCenter
from CommandCenter.models.inline_response20029_app_engine_types_app_engine_type import InlineResponse20029AppEngineTypesAppEngineType  # noqa: E501
from CommandCenter.rest import ApiException


class TestInlineResponse20029AppEngineTypesAppEngineType(unittest.TestCase):
    """InlineResponse20029AppEngineTypesAppEngineType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20029AppEngineTypesAppEngineType(self):
        """Test InlineResponse20029AppEngineTypesAppEngineType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CommandCenter.models.inline_response20029_app_engine_types_app_engine_type.InlineResponse20029AppEngineTypesAppEngineType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
