# coding: utf-8

"""
    Command Center operations

    Command Center operations  # noqa: E501

    OpenAPI spec version: 23.09
    Contact: support@zadarastorage.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import CommandCenter
from CommandCenter.models.inline_response200100_pools import InlineResponse200100Pools  # noqa: E501
from CommandCenter.rest import ApiException


class TestInlineResponse200100Pools(unittest.TestCase):
    """InlineResponse200100Pools unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse200100Pools(self):
        """Test InlineResponse200100Pools"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CommandCenter.models.inline_response200100_pools.InlineResponse200100Pools()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
