# coding: utf-8

"""
    Command Center operations

    Command Center operations  # noqa: E501

    OpenAPI spec version: 23.09
    Contact: support@zadarastorage.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import CommandCenter
from CommandCenter.models.inline_response200134_master_vc import InlineResponse200134MasterVc  # noqa: E501
from CommandCenter.rest import ApiException


class TestInlineResponse200134MasterVc(unittest.TestCase):
    """InlineResponse200134MasterVc unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse200134MasterVc(self):
        """Test InlineResponse200134MasterVc"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CommandCenter.models.inline_response200134_master_vc.InlineResponse200134MasterVc()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
