# coding: utf-8

"""
    Command Center operations

    Command Center operations  # noqa: E501

    OpenAPI spec version: 23.09
    Contact: support@zadarastorage.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import CommandCenter
from CommandCenter.models.inline_response2002_cloud_user import InlineResponse2002CloudUser  # noqa: E501
from CommandCenter.rest import ApiException


class TestInlineResponse2002CloudUser(unittest.TestCase):
    """InlineResponse2002CloudUser unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2002CloudUser(self):
        """Test InlineResponse2002CloudUser"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CommandCenter.models.inline_response2002_cloud_user.InlineResponse2002CloudUser()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
