# coding: utf-8

"""
    Command Center operations

    Command Center operations  # noqa: E501

    OpenAPI spec version: 23.09
    Contact: support@zadarastorage.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import CommandCenter
from CommandCenter.models.inline_response20091_fault_domains import InlineResponse20091FaultDomains  # noqa: E501
from CommandCenter.rest import ApiException


class TestInlineResponse20091FaultDomains(unittest.TestCase):
    """InlineResponse20091FaultDomains unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20091FaultDomains(self):
        """Test InlineResponse20091FaultDomains"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CommandCenter.models.inline_response20091_fault_domains.InlineResponse20091FaultDomains()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
