
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-04-18T11:54:25+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "dd814482255536d001e5a6958a6a7edc80a23015",
 "version": "0.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
