
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-04-19T14:40:59+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "500171569de25d49f6ddb3c167d9fc0e55cd66c7",
 "version": "0.10.2.post1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
