
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-04-15T19:52:20+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "7ecf3cfb6bca35947365af585b6f495a7fc4be92",
 "version": "1.0.0a2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
