
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-04-15T14:11:28-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "b3214579cfa372599d2c7d9c456bdaead1e007fd",
 "version": "1.28.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
