# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _OpenTelekomCloud


class _Security(_OpenTelekomCloud):
    _type = "security"
    _icon_dir = "resources/opentelekomcloud/security"


class AntiDdos(_Security):
    _icon = "anti-ddos.png"


class Kms(_Security):
    _icon = "kms.png"


class Wwaf(_Security):
    _icon = "wwaf.png"


# Aliases
