# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _OpenTelekomCloud


class _Storage(_OpenTelekomCloud):
    _type = "storage"
    _icon_dir = "resources/opentelekomcloud/storage"


class Cbr(_Storage):
    _icon = "cbr.png"


class Csbs(_Storage):
    _icon = "csbs.png"


class Evs(_Storage):
    _icon = "evs.png"


class Obs(_Storage):
    _icon = "obs.png"


class Sdrs(_Storage):
    _icon = "sdrs.png"


class Sfs(_Storage):
    _icon = "sfs.png"


class Vbs(_Storage):
    _icon = "vbs.png"


# Aliases
