"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.4.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.balance_sheet_liabilities_accounts import BalanceSheetLiabilitiesAccounts
globals()['BalanceSheetLiabilitiesAccounts'] = BalanceSheetLiabilitiesAccounts
from apideck.model.balance_sheet_liabilities import BalanceSheetLiabilities


class TestBalanceSheetLiabilities(unittest.TestCase):
    """BalanceSheetLiabilities unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBalanceSheetLiabilities(self):
        """Test BalanceSheetLiabilities"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BalanceSheetLiabilities()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
