
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-04-16T13:09:49+0100",
 "dirty": true,
 "error": null,
 "full-revisionid": "327b97df06ce7f81bd582f216604829e9fbc9e69",
 "version": "1.1.4.post0.dev12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
