# Generated by Django 4.2.9 on 2024-01-29 08:16

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('slurpit_nautobot', '0002_auto_20240317_1425'),
    ]

    operations = [
        migrations.RunSQL(
            """
            UPDATE extras_customfield
            SET key = 'slurpit_manufacturer',
                label = 'Manufacturer'
            WHERE key = 'slurpit_manufactor'
            """,
        ),
        migrations.RunSQL(
            """
            UPDATE dcim_device
            SET _custom_field_data = jsonb_set(_custom_field_data, '{slurpit_manufacturer}', _custom_field_data -> 'slurpit_manufactor', true)
            """,
        ),
    ]
