
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-04-17T15:55:41-0500",
 "dirty": true,
 "error": null,
 "full-revisionid": "337682e2b4e251a2601eaa8807dd30aca1fe38a4",
 "version": "0.5.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
