import ghidra.program.model.address
import ghidra.program.model.pcode
import java.io
import java.lang


class PackedEncode(object, ghidra.program.model.pcode.PatchEncoder):
    """
    A byte-based encoder designed to marshal to the decompiler efficiently
     See  for details of the encoding format
    """





    def __init__(self): ...



    def clear(self) -> None: ...

    def closeElement(self, elemId: ghidra.program.model.pcode.ElementId) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def hashCode(self) -> int: ...

    def isEmpty(self) -> bool: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def openElement(self, elemId: ghidra.program.model.pcode.ElementId) -> None: ...

    def patchIntegerAttribute(self, pos: int, attribId: ghidra.program.model.pcode.AttributeId, val: long) -> bool: ...

    def size(self) -> int: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    def writeBool(self, attribId: ghidra.program.model.pcode.AttributeId, val: bool) -> None: ...

    def writeSignedInteger(self, attribId: ghidra.program.model.pcode.AttributeId, val: long) -> None: ...

    def writeSpace(self, attribId: ghidra.program.model.pcode.AttributeId, spc: ghidra.program.model.address.AddressSpace) -> None: ...

    def writeSpaceId(self, attribId: ghidra.program.model.pcode.AttributeId, spaceId: long) -> None: ...

    def writeString(self, attribId: ghidra.program.model.pcode.AttributeId, val: unicode) -> None: ...

    def writeStringIndexed(self, attribId: ghidra.program.model.pcode.AttributeId, index: int, val: unicode) -> None: ...

    def writeTo(self, stream: java.io.OutputStream) -> None: ...

    def writeUnsignedInteger(self, attribId: ghidra.program.model.pcode.AttributeId, val: long) -> None: ...

    @property
    def empty(self) -> bool: ...