# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: com/terraquantum/user/v2/waiting_user/get_waiting_user_request.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nDcom/terraquantum/user/v2/waiting_user/get_waiting_user_request.proto\x12%com.terraquantum.user.v2.waiting_user\"-\n\x15GetWaitingUserRequest\x12\x14\n\x05\x65mail\x18\x01 \x01(\tR\x05\x65mailB\xc8\x02\n)com.com.terraquantum.user.v2.waiting_userB\x1aGetWaitingUserRequestProtoP\x01ZIterraquantum.swiss/tq42_grpc_client/com/terraquantum/user/v2/waiting_user\xa2\x02\x05\x43TUVW\xaa\x02$Com.Terraquantum.User.V2.WaitingUser\xca\x02$Com\\Terraquantum\\User\\V2\\WaitingUser\xe2\x02\x30\x43om\\Terraquantum\\User\\V2\\WaitingUser\\GPBMetadata\xea\x02(Com::Terraquantum::User::V2::WaitingUserb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'com.terraquantum.user.v2.waiting_user.get_waiting_user_request_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n)com.com.terraquantum.user.v2.waiting_userB\032GetWaitingUserRequestProtoP\001ZIterraquantum.swiss/tq42_grpc_client/com/terraquantum/user/v2/waiting_user\242\002\005CTUVW\252\002$Com.Terraquantum.User.V2.WaitingUser\312\002$Com\\Terraquantum\\User\\V2\\WaitingUser\342\0020Com\\Terraquantum\\User\\V2\\WaitingUser\\GPBMetadata\352\002(Com::Terraquantum::User::V2::WaitingUser'
  _globals['_GETWAITINGUSERREQUEST']._serialized_start=111
  _globals['_GETWAITINGUSERREQUEST']._serialized_end=156
# @@protoc_insertion_point(module_scope)
