
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-04-19T14:45:02+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "9fd98cccf06a31c18a09e30e57a911d8ec482872",
 "version": "0.10.2.post1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
