# Generated by Django 3.2.24 on 2024-04-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slurpit_nautobot', '0003_manufacturer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slurpitstageddevice',
            options={'ordering': ('hostname',), 'verbose_name': 'device', 'verbose_name_plural': 'device'},
        ),
        migrations.AddField(
            model_name='slurpitsnapshot',
            name='result_type',
            field=models.CharField(default='template_result', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='slurpitstageddevice',
            unique_together={('hostname',)},
        ),
    ]
