# This file automatically generated by
#    /home/couchbase/jenkins/workspace/python/sdk/python-packaging-pipeline/py-client-docs/couchbase_version.py
# at
#    2024-04-18 14:41:23.586705
__version__ = '4.2.1rc1'