# Generated by Django 2.2.28 on 2023-06-15 16:05

# Django
import django.db.models.deletion
from django.db import migrations, models

# Third party
import ckeditor_uploader.fields
import filer.fields.file
import taggit_autosuggest.managers


class Migration(migrations.Migration):

    dependencies = [
        ("filer", "0015_alter_file_owner_alter_file_polymorphic_ctype_and_more"),
        ("django_simple_notes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simplenote",
            name="categories",
            field=taggit_autosuggest.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AlterField(
            model_name="simplenote",
            name="note",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.CreateModel(
            name="SimpleFile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    filer.fields.file.FilerFileField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="filer.File",
                    ),
                ),
                (
                    "note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_simple_notes.SimpleNote",
                    ),
                ),
            ],
        ),
    ]
