# Generated by Django 2.2.28 on 2023-06-20 10:07

# Django
import django.db.models.deletion
from django.db import migrations, models

# Third party
import ckeditor_uploader.fields
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ("django_simple_notes", "0002_auto_20230615_1805"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="simplefile",
            options={
                "verbose_name": "Extra file",
                "verbose_name_plural": "Extra files",
            },
        ),
        migrations.AlterModelOptions(
            name="simplenote",
            options={"verbose_name": "note", "verbose_name_plural": "Simple notes"},
        ),
        migrations.AlterField(
            model_name="simplefile",
            name="file",
            field=filer.fields.file.FilerFileField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="filer.File",
                verbose_name="Files",
            ),
        ),
        migrations.AlterField(
            model_name="simplenote",
            name="author",
            field=models.CharField(max_length=128, verbose_name="Author"),
        ),
        migrations.AlterField(
            model_name="simplenote",
            name="note",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True
            ),
        ),
    ]
