# Generated by Django 3.2.22 on 2023-10-30 16:51

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
        ("django_simple_notes", "0004_auto_20230620_1452"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="simplenote",
            options={
                "verbose_name": "note privée",
                "verbose_name_plural": "Book Accueil",
            },
        ),
        migrations.AddField(
            model_name="simplenote",
            name="site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="sites.site",
            ),
        ),
    ]
