
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-04-12T18:06:46+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "9095b0aebd0ed705a38a669b85da16310a714468",
 "version": "5.3.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
