from typing import List
import ghidra.pcode.emu.sys
import java.lang


class BytesEmuFileContents(object, ghidra.pcode.emu.sys.EmuFileContents):




    def __init__(self): ...



    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    @overload
    def read(self, __a0: long, __a1: List[int], __a2: long) -> long: ...

    @overload
    def read(self, __a0: long, __a1: object, __a2: long) -> long: ...

    def toString(self) -> unicode: ...

    def truncate(self) -> None: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @overload
    def write(self, __a0: long, __a1: List[int], __a2: long) -> long: ...

    @overload
    def write(self, __a0: long, __a1: object, __a2: long) -> long: ...

