
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-04-17T09:55:39-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "8b738135ce6c7b5dc1b5ffddf56f4b4d23a770e7",
 "version": "0.4.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
