BEAD_RING_DIAMETER_TO_RIM_DIAMETER = 1.06
BEAD_RING_INNER_DIAMETER_TO_RIM_DIAMETER = .65
BEAD_RING_HEIGHT_TO_TYRE_WIDTH = .25
CENTER_RING_DIAMETER_TO_RIM_DIAMETER = .9
CENTER_RING_INNER_DIAMETER_TO_RIM_DIAMETER = .65
CENTER_RING_HEIGHT_TO_TYRE_WIDTH = .1
CLAMP_RING_DIAMETER_TO_RIM_DIAMETER = .8
CLAMP_RING_INNER_DIAMETER_TO_RIM_DIAMETER = .1
CLAMP_RING_HEIGHT_TO_TYRE_WIDTH = .25

MOULD_2PCS_MIN_HOR_TK = 40
MOULD_2PCS_HOR_TK_POWER_RATE = .202
MOULD_2PCS_MIN_VER_TK = 35
MOULD_2PCS_VER_TK_POWER_RATE = .197
MOULD_INNER_DIAMETER_TO_RIM_DIAMETER = .65

