"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.4.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.balance_sheet_assets_current_assets import BalanceSheetAssetsCurrentAssets
from apideck.model.balance_sheet_assets_fixed_assets import BalanceSheetAssetsFixedAssets
globals()['BalanceSheetAssetsCurrentAssets'] = BalanceSheetAssetsCurrentAssets
globals()['BalanceSheetAssetsFixedAssets'] = BalanceSheetAssetsFixedAssets
from apideck.model.balance_sheet_assets import BalanceSheetAssets


class TestBalanceSheetAssets(unittest.TestCase):
    """BalanceSheetAssets unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBalanceSheetAssets(self):
        """Test BalanceSheetAssets"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BalanceSheetAssets()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
