
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-04-18T10:01:28+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "92e2ee5cbaf461f8d40eedd666b8f722d1003c38",
 "version": "0.66"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
