# coding: utf-8

"""
    moon-vault-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictStr
from pydantic import Field
from moonsdk.models.trigger_output import TriggerOutput
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class IERC20Approval(BaseModel):
    """
    IERC20Approval
    """ # noqa: E501
    transaction_hash: StrictStr = Field(alias="transactionHash")
    contract: StrictStr
    log_index: StrictStr = Field(alias="logIndex")
    owner: StrictStr
    spender: StrictStr
    value: StrictStr
    token_decimals: StrictStr = Field(alias="tokenDecimals")
    token_name: StrictStr = Field(alias="tokenName")
    token_symbol: StrictStr = Field(alias="tokenSymbol")
    value_with_decimals: Optional[StrictStr] = Field(default=None, alias="valueWithDecimals")
    triggers: Optional[List[TriggerOutput]] = None
    __properties: ClassVar[List[str]] = ["transactionHash", "contract", "logIndex", "owner", "spender", "value", "tokenDecimals", "tokenName", "tokenSymbol", "valueWithDecimals", "triggers"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of IERC20Approval from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in triggers (list)
        _items = []
        if self.triggers:
            for _item in self.triggers:
                if _item:
                    _items.append(_item.to_dict())
            _dict['triggers'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of IERC20Approval from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "transactionHash": obj.get("transactionHash"),
            "contract": obj.get("contract"),
            "logIndex": obj.get("logIndex"),
            "owner": obj.get("owner"),
            "spender": obj.get("spender"),
            "value": obj.get("value"),
            "tokenDecimals": obj.get("tokenDecimals"),
            "tokenName": obj.get("tokenName"),
            "tokenSymbol": obj.get("tokenSymbol"),
            "valueWithDecimals": obj.get("valueWithDecimals"),
            "triggers": [TriggerOutput.from_dict(_item) for _item in obj.get("triggers")] if obj.get("triggers") is not None else None
        })
        return _obj


