# coding: utf-8

"""
    moon-vault-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictBool, StrictStr
from pydantic import Field
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class INFTApproval(BaseModel):
    """
    INFTApproval
    """ # noqa: E501
    transaction_hash: StrictStr = Field(alias="transactionHash")
    contract: StrictStr
    log_index: StrictStr = Field(alias="logIndex")
    token_contract_type: StrictStr = Field(alias="tokenContractType")
    token_name: StrictStr = Field(alias="tokenName")
    token_symbol: StrictStr = Field(alias="tokenSymbol")
    account: StrictStr
    operator: StrictStr
    approved_all: StrictBool = Field(alias="approvedAll")
    token_id: Optional[StrictStr] = Field(alias="tokenId")
    __properties: ClassVar[List[str]] = ["transactionHash", "contract", "logIndex", "tokenContractType", "tokenName", "tokenSymbol", "account", "operator", "approvedAll", "tokenId"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of INFTApproval from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # set to None if token_id (nullable) is None
        # and model_fields_set contains the field
        if self.token_id is None and "token_id" in self.model_fields_set:
            _dict['tokenId'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of INFTApproval from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "transactionHash": obj.get("transactionHash"),
            "contract": obj.get("contract"),
            "logIndex": obj.get("logIndex"),
            "tokenContractType": obj.get("tokenContractType"),
            "tokenName": obj.get("tokenName"),
            "tokenSymbol": obj.get("tokenSymbol"),
            "account": obj.get("account"),
            "operator": obj.get("operator"),
            "approvedAll": obj.get("approvedAll"),
            "tokenId": obj.get("tokenId")
        })
        return _obj


