
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-04-15T14:06:06-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "78c093c210159c7eea5e932e550952b3dabab5f2",
 "version": "1.23.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
