# Generated by Django 2.2.15 on 2020-11-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fperms', '0004_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='codename',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True,
                                   verbose_name='codename'),
        ),
        migrations.AlterField(
            model_name='perm',
            name='codename',
            field=models.CharField(db_index=True, max_length=100, verbose_name='codename'),
        ),
        migrations.AlterField(
            model_name='perm',
            name='object_id',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='object pk'),
        ),
    ]
