# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OD2d.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import generated_proto_pycode.common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nOD2d.proto\x12\x07ld_grpc\x1a\x0c\x63ommon.proto\"~\n\rImageBBoxList\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\x10\n\x08\x66rame_id\x18\x02 \x01(\r\x12\x12\n\nimg_height\x18\x03 \x01(\r\x12\x11\n\timg_width\x18\x04 \x01(\r\x12!\n\x05\x62oxes\x18\x05 \x03(\x0b\x32\x12.ld_grpc.ImageBBox\"\x92\x02\n\tImageBBox\x12\n\n\x02id\x18\x01 \x01(\r\x12\r\n\x05id_3d\x18\x02 \x01(\r\x12\x10\n\x08\x63\x61tegory\x18\x03 \x01(\t\x12\x0f\n\x07iscrowd\x18\x04 \x01(\x08\x12\x12\n\nisoccluded\x18\x05 \x01(\x08\x12\x1e\n\x04\x62\x62ox\x18\x06 \x03(\x0b\x32\x10.ld_grpc.Point3f\x12!\n\x07\x62\x62ox_3d\x18\x07 \x03(\x0b\x32\x10.ld_grpc.Point3f\x12#\n\tref_point\x18\x08 \x01(\x0b\x32\x10.ld_grpc.Point3f\x12#\n\tdimension\x18\t \x01(\x0b\x32\x10.ld_grpc.Point3f\x12\x18\n\x10segmentation_rle\x18\n \x03(\r\x12\x0c\n\x04\x61rea\x18\x0b \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'OD2d_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_IMAGEBBOXLIST']._serialized_start=37
  _globals['_IMAGEBBOXLIST']._serialized_end=163
  _globals['_IMAGEBBOX']._serialized_start=166
  _globals['_IMAGEBBOX']._serialized_end=440
# @@protoc_insertion_point(module_scope)
