# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x1a\x1cgoogle/api/annotations.proto\"\x1c\n\x0b\x45\x63hoMessage\x12\r\n\x05value\x18\x01 \x01(\t2F\n\x0b\x45\x63hoService\x12\x37\n\x04\x45\x63ho\x12\x0c.EchoMessage\x1a\x0c.EchoMessage\"\x13\x82\xd3\xe4\x93\x02\r\"\x08/v1/echo:\x01*b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _ECHOSERVICE.methods_by_name['Echo']._options = None
  _ECHOSERVICE.methods_by_name['Echo']._serialized_options = b'\202\323\344\223\002\r\"\010/v1/echo:\001*'
  _globals['_ECHOMESSAGE']._serialized_start=47
  _globals['_ECHOMESSAGE']._serialized_end=75
  _globals['_ECHOSERVICE']._serialized_start=77
  _globals['_ECHOSERVICE']._serialized_end=147
# @@protoc_insertion_point(module_scope)
